global using MSAFocus_TechnicalAssessment.Domain.Common;
global using MSAFocus_TechnicalAssessment.Domain.Entities;
global using MSAFocus_TechnicalAssessment.Domain.Enums;
global using MSAFocus_TechnicalAssessment.Domain.Events;
global using MSAFocus_TechnicalAssessment.Domain.Exceptions;
global using MSAFocus_TechnicalAssessment.Domain.ValueObjects;